"#000000": Black
"#808080": Gray
"#FFFFFF": White
"#FF00FF": Fuchsia
"#800080": Purple
"#ff0000": Red
"#800000": Maroon 
"#8b4513": Brown
"#ffff00": Yellow
"#808000": Olive
"#00ff00": Lime
"#008000": Green
"#00ffff": Aqua
"#008080": Teal
"#0000ff": Blue
"#000080": Navy
"#f5deb3": Wheat
"#a0522d": Sienna
"#ffdab9": PeachPuff
"#4b0082": Indigo
"#9400d3": DarkViolet
"#ff1493": DeepPink
"#dc143c": Crimson